// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: test.proto

package notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Priority enum for notification priority
type Priority int32

const (
	Priority_NORMAL Priority = 0
	Priority_HIGH   Priority = 1
	Priority_URGENT Priority = 2
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "NORMAL",
		1: "HIGH",
		2: "URGENT",
	}
	Priority_value = map[string]int32{
		"NORMAL": 0,
		"HIGH":   1,
		"URGENT": 2,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

// NotificationMessage represents different types of notifications
type NotificationMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// First level oneof - notification type
	//
	// Types that are valid to be assigned to DeliveryChannel:
	//
	//	*NotificationMessage_Email
	//	*NotificationMessage_Sms
	//	*NotificationMessage_Push
	DeliveryChannel isNotificationMessage_DeliveryChannel `protobuf_oneof:"delivery_channel"`
	Priority        Priority                              `protobuf:"varint,6,opt,name=priority,proto3,enum=notification.Priority" json:"priority,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NotificationMessage) Reset() {
	*x = NotificationMessage{}
	mi := &file_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationMessage) ProtoMessage() {}

func (x *NotificationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationMessage.ProtoReflect.Descriptor instead.
func (*NotificationMessage) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotificationMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *NotificationMessage) GetDeliveryChannel() isNotificationMessage_DeliveryChannel {
	if x != nil {
		return x.DeliveryChannel
	}
	return nil
}

func (x *NotificationMessage) GetEmail() *EmailNotification {
	if x != nil {
		if x, ok := x.DeliveryChannel.(*NotificationMessage_Email); ok {
			return x.Email
		}
	}
	return nil
}

func (x *NotificationMessage) GetSms() *SMSNotification {
	if x != nil {
		if x, ok := x.DeliveryChannel.(*NotificationMessage_Sms); ok {
			return x.Sms
		}
	}
	return nil
}

func (x *NotificationMessage) GetPush() *PushNotification {
	if x != nil {
		if x, ok := x.DeliveryChannel.(*NotificationMessage_Push); ok {
			return x.Push
		}
	}
	return nil
}

func (x *NotificationMessage) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_NORMAL
}

type isNotificationMessage_DeliveryChannel interface {
	isNotificationMessage_DeliveryChannel()
}

type NotificationMessage_Email struct {
	Email *EmailNotification `protobuf:"bytes,3,opt,name=email,proto3,oneof"`
}

type NotificationMessage_Sms struct {
	Sms *SMSNotification `protobuf:"bytes,4,opt,name=sms,proto3,oneof"`
}

type NotificationMessage_Push struct {
	Push *PushNotification `protobuf:"bytes,5,opt,name=push,proto3,oneof"`
}

func (*NotificationMessage_Email) isNotificationMessage_DeliveryChannel() {}

func (*NotificationMessage_Sms) isNotificationMessage_DeliveryChannel() {}

func (*NotificationMessage_Push) isNotificationMessage_DeliveryChannel() {}

// EmailNotification contains email-specific fields
type EmailNotification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RecipientEmail string                 `protobuf:"bytes,1,opt,name=recipient_email,json=recipientEmail,proto3" json:"recipient_email,omitempty"`
	Subject        string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// Second level oneof - content type
	//
	// Types that are valid to be assigned to Content:
	//
	//	*EmailNotification_PlainText
	//	*EmailNotification_Html
	//	*EmailNotification_RichContent
	Content       isEmailNotification_Content `protobuf_oneof:"content"`
	Cc            []string                    `protobuf:"bytes,6,rep,name=cc,proto3" json:"cc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailNotification) Reset() {
	*x = EmailNotification{}
	mi := &file_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailNotification) ProtoMessage() {}

func (x *EmailNotification) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailNotification.ProtoReflect.Descriptor instead.
func (*EmailNotification) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *EmailNotification) GetRecipientEmail() string {
	if x != nil {
		return x.RecipientEmail
	}
	return ""
}

func (x *EmailNotification) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailNotification) GetContent() isEmailNotification_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *EmailNotification) GetPlainText() string {
	if x != nil {
		if x, ok := x.Content.(*EmailNotification_PlainText); ok {
			return x.PlainText
		}
	}
	return ""
}

func (x *EmailNotification) GetHtml() string {
	if x != nil {
		if x, ok := x.Content.(*EmailNotification_Html); ok {
			return x.Html
		}
	}
	return ""
}

func (x *EmailNotification) GetRichContent() *RichContent {
	if x != nil {
		if x, ok := x.Content.(*EmailNotification_RichContent); ok {
			return x.RichContent
		}
	}
	return nil
}

func (x *EmailNotification) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

type isEmailNotification_Content interface {
	isEmailNotification_Content()
}

type EmailNotification_PlainText struct {
	PlainText string `protobuf:"bytes,3,opt,name=plain_text,json=plainText,proto3,oneof"`
}

type EmailNotification_Html struct {
	Html string `protobuf:"bytes,4,opt,name=html,proto3,oneof"`
}

type EmailNotification_RichContent struct {
	RichContent *RichContent `protobuf:"bytes,5,opt,name=rich_content,json=richContent,proto3,oneof"`
}

func (*EmailNotification_PlainText) isEmailNotification_Content() {}

func (*EmailNotification_Html) isEmailNotification_Content() {}

func (*EmailNotification_RichContent) isEmailNotification_Content() {}

// SMSNotification contains SMS-specific fields
type SMSNotification struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// Second level oneof - content type
	//
	// Types that are valid to be assigned to Content:
	//
	//	*SMSNotification_Text
	//	*SMSNotification_Media
	Content       isSMSNotification_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SMSNotification) Reset() {
	*x = SMSNotification{}
	mi := &file_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SMSNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMSNotification) ProtoMessage() {}

func (x *SMSNotification) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMSNotification.ProtoReflect.Descriptor instead.
func (*SMSNotification) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

func (x *SMSNotification) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *SMSNotification) GetContent() isSMSNotification_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SMSNotification) GetText() string {
	if x != nil {
		if x, ok := x.Content.(*SMSNotification_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *SMSNotification) GetMedia() *MediaContent {
	if x != nil {
		if x, ok := x.Content.(*SMSNotification_Media); ok {
			return x.Media
		}
	}
	return nil
}

type isSMSNotification_Content interface {
	isSMSNotification_Content()
}

type SMSNotification_Text struct {
	Text string `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type SMSNotification_Media struct {
	Media *MediaContent `protobuf:"bytes,3,opt,name=media,proto3,oneof"`
}

func (*SMSNotification_Text) isSMSNotification_Content() {}

func (*SMSNotification_Media) isSMSNotification_Content() {}

// PushNotification contains push notification fields
type PushNotification struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	DeviceToken string                 `protobuf:"bytes,1,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	// Second level oneof - notification style
	//
	// Types that are valid to be assigned to Style:
	//
	//	*PushNotification_Basic
	//	*PushNotification_Alert
	Style         isPushNotification_Style `protobuf_oneof:"style"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushNotification) Reset() {
	*x = PushNotification{}
	mi := &file_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushNotification) ProtoMessage() {}

func (x *PushNotification) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushNotification.ProtoReflect.Descriptor instead.
func (*PushNotification) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{3}
}

func (x *PushNotification) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

func (x *PushNotification) GetStyle() isPushNotification_Style {
	if x != nil {
		return x.Style
	}
	return nil
}

func (x *PushNotification) GetBasic() *BasicNotification {
	if x != nil {
		if x, ok := x.Style.(*PushNotification_Basic); ok {
			return x.Basic
		}
	}
	return nil
}

func (x *PushNotification) GetAlert() *AlertNotification {
	if x != nil {
		if x, ok := x.Style.(*PushNotification_Alert); ok {
			return x.Alert
		}
	}
	return nil
}

type isPushNotification_Style interface {
	isPushNotification_Style()
}

type PushNotification_Basic struct {
	Basic *BasicNotification `protobuf:"bytes,2,opt,name=basic,proto3,oneof"`
}

type PushNotification_Alert struct {
	Alert *AlertNotification `protobuf:"bytes,3,opt,name=alert,proto3,oneof"`
}

func (*PushNotification_Basic) isPushNotification_Style() {}

func (*PushNotification_Alert) isPushNotification_Style() {}

// BasicNotification for simple push notifications
type BasicNotification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Title string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body  string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	// Third level oneof - action type
	//
	// Types that are valid to be assigned to Action:
	//
	//	*BasicNotification_Url
	//	*BasicNotification_AppRoute
	Action        isBasicNotification_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicNotification) Reset() {
	*x = BasicNotification{}
	mi := &file_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicNotification) ProtoMessage() {}

func (x *BasicNotification) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicNotification.ProtoReflect.Descriptor instead.
func (*BasicNotification) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4}
}

func (x *BasicNotification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BasicNotification) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *BasicNotification) GetAction() isBasicNotification_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *BasicNotification) GetUrl() string {
	if x != nil {
		if x, ok := x.Action.(*BasicNotification_Url); ok {
			return x.Url
		}
	}
	return ""
}

func (x *BasicNotification) GetAppRoute() string {
	if x != nil {
		if x, ok := x.Action.(*BasicNotification_AppRoute); ok {
			return x.AppRoute
		}
	}
	return ""
}

type isBasicNotification_Action interface {
	isBasicNotification_Action()
}

type BasicNotification_Url struct {
	Url string `protobuf:"bytes,3,opt,name=url,proto3,oneof"`
}

type BasicNotification_AppRoute struct {
	AppRoute string `protobuf:"bytes,4,opt,name=app_route,json=appRoute,proto3,oneof"`
}

func (*BasicNotification_Url) isBasicNotification_Action() {}

func (*BasicNotification_AppRoute) isBasicNotification_Action() {}

// AlertNotification for more urgent push notifications
type AlertNotification struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Title               string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body                string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	RequiresInteraction bool                   `protobuf:"varint,3,opt,name=requires_interaction,json=requiresInteraction,proto3" json:"requires_interaction,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AlertNotification) Reset() {
	*x = AlertNotification{}
	mi := &file_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertNotification) ProtoMessage() {}

func (x *AlertNotification) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertNotification.ProtoReflect.Descriptor instead.
func (*AlertNotification) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{5}
}

func (x *AlertNotification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AlertNotification) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *AlertNotification) GetRequiresInteraction() bool {
	if x != nil {
		return x.RequiresInteraction
	}
	return false
}

// RichContent represents complex content
type RichContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Html          string                 `protobuf:"bytes,1,opt,name=html,proto3" json:"html,omitempty"`
	Attachments   []*Attachment          `protobuf:"bytes,2,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RichContent) Reset() {
	*x = RichContent{}
	mi := &file_test_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RichContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RichContent) ProtoMessage() {}

func (x *RichContent) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RichContent.ProtoReflect.Descriptor instead.
func (*RichContent) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{6}
}

func (x *RichContent) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *RichContent) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

// MediaContent for SMS with media
type MediaContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	MediaData     []byte                 `protobuf:"bytes,2,opt,name=media_data,json=mediaData,proto3" json:"media_data,omitempty"`
	MediaType     string                 `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaContent) Reset() {
	*x = MediaContent{}
	mi := &file_test_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaContent) ProtoMessage() {}

func (x *MediaContent) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaContent.ProtoReflect.Descriptor instead.
func (*MediaContent) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{7}
}

func (x *MediaContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MediaContent) GetMediaData() []byte {
	if x != nil {
		return x.MediaData
	}
	return nil
}

func (x *MediaContent) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

// Attachment for email attachments
type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_test_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{8}
}

func (x *Attachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Attachment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Attachment) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

var File_test_proto protoreflect.FileDescriptor

const file_test_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"test.proto\x12\fnotification\"\xad\x02\n" +
	"\x13NotificationMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x127\n" +
	"\x05email\x18\x03 \x01(\v2\x1f.notification.EmailNotificationH\x00R\x05email\x121\n" +
	"\x03sms\x18\x04 \x01(\v2\x1d.notification.SMSNotificationH\x00R\x03sms\x124\n" +
	"\x04push\x18\x05 \x01(\v2\x1e.notification.PushNotificationH\x00R\x04push\x122\n" +
	"\bpriority\x18\x06 \x01(\x0e2\x16.notification.PriorityR\bpriorityB\x12\n" +
	"\x10delivery_channel\"\xe8\x01\n" +
	"\x11EmailNotification\x12'\n" +
	"\x0frecipient_email\x18\x01 \x01(\tR\x0erecipientEmail\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1f\n" +
	"\n" +
	"plain_text\x18\x03 \x01(\tH\x00R\tplainText\x12\x14\n" +
	"\x04html\x18\x04 \x01(\tH\x00R\x04html\x12>\n" +
	"\frich_content\x18\x05 \x01(\v2\x19.notification.RichContentH\x00R\vrichContent\x12\x0e\n" +
	"\x02cc\x18\x06 \x03(\tR\x02ccB\t\n" +
	"\acontent\"\x89\x01\n" +
	"\x0fSMSNotification\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x04text\x18\x02 \x01(\tH\x00R\x04text\x122\n" +
	"\x05media\x18\x03 \x01(\v2\x1a.notification.MediaContentH\x00R\x05mediaB\t\n" +
	"\acontent\"\xb0\x01\n" +
	"\x10PushNotification\x12!\n" +
	"\fdevice_token\x18\x01 \x01(\tR\vdeviceToken\x127\n" +
	"\x05basic\x18\x02 \x01(\v2\x1f.notification.BasicNotificationH\x00R\x05basic\x127\n" +
	"\x05alert\x18\x03 \x01(\v2\x1f.notification.AlertNotificationH\x00R\x05alertB\a\n" +
	"\x05style\"z\n" +
	"\x11BasicNotification\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x12\n" +
	"\x03url\x18\x03 \x01(\tH\x00R\x03url\x12\x1d\n" +
	"\tapp_route\x18\x04 \x01(\tH\x00R\bappRouteB\b\n" +
	"\x06action\"p\n" +
	"\x11AlertNotification\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x121\n" +
	"\x14requires_interaction\x18\x03 \x01(\bR\x13requiresInteraction\"]\n" +
	"\vRichContent\x12\x12\n" +
	"\x04html\x18\x01 \x01(\tR\x04html\x12:\n" +
	"\vattachments\x18\x02 \x03(\v2\x18.notification.AttachmentR\vattachments\"`\n" +
	"\fMediaContent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"media_data\x18\x02 \x01(\fR\tmediaData\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\"Y\n" +
	"\n" +
	"Attachment\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType*,\n" +
	"\bPriority\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x00\x12\b\n" +
	"\x04HIGH\x10\x01\x12\n" +
	"\n" +
	"\x06URGENT\x10\x02B!Z\x1fgithub.com/example/notificationb\x06proto3"

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData []byte
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)))
	})
	return file_test_proto_rawDescData
}

var file_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_test_proto_goTypes = []any{
	(Priority)(0),               // 0: notification.Priority
	(*NotificationMessage)(nil), // 1: notification.NotificationMessage
	(*EmailNotification)(nil),   // 2: notification.EmailNotification
	(*SMSNotification)(nil),     // 3: notification.SMSNotification
	(*PushNotification)(nil),    // 4: notification.PushNotification
	(*BasicNotification)(nil),   // 5: notification.BasicNotification
	(*AlertNotification)(nil),   // 6: notification.AlertNotification
	(*RichContent)(nil),         // 7: notification.RichContent
	(*MediaContent)(nil),        // 8: notification.MediaContent
	(*Attachment)(nil),          // 9: notification.Attachment
}
var file_test_proto_depIdxs = []int32{
	2, // 0: notification.NotificationMessage.email:type_name -> notification.EmailNotification
	3, // 1: notification.NotificationMessage.sms:type_name -> notification.SMSNotification
	4, // 2: notification.NotificationMessage.push:type_name -> notification.PushNotification
	0, // 3: notification.NotificationMessage.priority:type_name -> notification.Priority
	7, // 4: notification.EmailNotification.rich_content:type_name -> notification.RichContent
	8, // 5: notification.SMSNotification.media:type_name -> notification.MediaContent
	5, // 6: notification.PushNotification.basic:type_name -> notification.BasicNotification
	6, // 7: notification.PushNotification.alert:type_name -> notification.AlertNotification
	9, // 8: notification.RichContent.attachments:type_name -> notification.Attachment
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	file_test_proto_msgTypes[0].OneofWrappers = []any{
		(*NotificationMessage_Email)(nil),
		(*NotificationMessage_Sms)(nil),
		(*NotificationMessage_Push)(nil),
	}
	file_test_proto_msgTypes[1].OneofWrappers = []any{
		(*EmailNotification_PlainText)(nil),
		(*EmailNotification_Html)(nil),
		(*EmailNotification_RichContent)(nil),
	}
	file_test_proto_msgTypes[2].OneofWrappers = []any{
		(*SMSNotification_Text)(nil),
		(*SMSNotification_Media)(nil),
	}
	file_test_proto_msgTypes[3].OneofWrappers = []any{
		(*PushNotification_Basic)(nil),
		(*PushNotification_Alert)(nil),
	}
	file_test_proto_msgTypes[4].OneofWrappers = []any{
		(*BasicNotification_Url)(nil),
		(*BasicNotification_AppRoute)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		EnumInfos:         file_test_proto_enumTypes,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
