// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: test.proto

package notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum definitions
type NotificationType int32

const (
	NotificationType_TYPE_UNKNOWN NotificationType = 0
	NotificationType_TYPE_EMAIL   NotificationType = 1
	NotificationType_TYPE_SMS     NotificationType = 2
	NotificationType_TYPE_PUSH    NotificationType = 3
	NotificationType_TYPE_WEBHOOK NotificationType = 4
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "TYPE_UNKNOWN",
		1: "TYPE_EMAIL",
		2: "TYPE_SMS",
		3: "TYPE_PUSH",
		4: "TYPE_WEBHOOK",
	}
	NotificationType_value = map[string]int32{
		"TYPE_UNKNOWN": 0,
		"TYPE_EMAIL":   1,
		"TYPE_SMS":     2,
		"TYPE_PUSH":    3,
		"TYPE_WEBHOOK": 4,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

type Priority int32

const (
	Priority_PRIORITY_UNKNOWN Priority = 0
	Priority_PRIORITY_LOW     Priority = 1
	Priority_PRIORITY_MEDIUM  Priority = 2
	Priority_PRIORITY_HIGH    Priority = 3
	Priority_PRIORITY_URGENT  Priority = 4
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNKNOWN",
		1: "PRIORITY_LOW",
		2: "PRIORITY_MEDIUM",
		3: "PRIORITY_HIGH",
		4: "PRIORITY_URGENT",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNKNOWN": 0,
		"PRIORITY_LOW":     1,
		"PRIORITY_MEDIUM":  2,
		"PRIORITY_HIGH":    3,
		"PRIORITY_URGENT":  4,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[1].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[1]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

type Status int32

const (
	Status_STATUS_UNKNOWN   Status = 0
	Status_STATUS_PENDING   Status = 1
	Status_STATUS_SENT      Status = 2
	Status_STATUS_DELIVERED Status = 3
	Status_STATUS_FAILED    Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_PENDING",
		2: "STATUS_SENT",
		3: "STATUS_DELIVERED",
		4: "STATUS_FAILED",
	}
	Status_value = map[string]int32{
		"STATUS_UNKNOWN":   0,
		"STATUS_PENDING":   1,
		"STATUS_SENT":      2,
		"STATUS_DELIVERED": 3,
		"STATUS_FAILED":    4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[2].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[2]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

type ScheduleConfig_DayOfWeek int32

const (
	ScheduleConfig_DAY_UNKNOWN ScheduleConfig_DayOfWeek = 0
	ScheduleConfig_MONDAY      ScheduleConfig_DayOfWeek = 1
	ScheduleConfig_TUESDAY     ScheduleConfig_DayOfWeek = 2
	ScheduleConfig_WEDNESDAY   ScheduleConfig_DayOfWeek = 3
	ScheduleConfig_THURSDAY    ScheduleConfig_DayOfWeek = 4
	ScheduleConfig_FRIDAY      ScheduleConfig_DayOfWeek = 5
	ScheduleConfig_SATURDAY    ScheduleConfig_DayOfWeek = 6
	ScheduleConfig_SUNDAY      ScheduleConfig_DayOfWeek = 7
)

// Enum value maps for ScheduleConfig_DayOfWeek.
var (
	ScheduleConfig_DayOfWeek_name = map[int32]string{
		0: "DAY_UNKNOWN",
		1: "MONDAY",
		2: "TUESDAY",
		3: "WEDNESDAY",
		4: "THURSDAY",
		5: "FRIDAY",
		6: "SATURDAY",
		7: "SUNDAY",
	}
	ScheduleConfig_DayOfWeek_value = map[string]int32{
		"DAY_UNKNOWN": 0,
		"MONDAY":      1,
		"TUESDAY":     2,
		"WEDNESDAY":   3,
		"THURSDAY":    4,
		"FRIDAY":      5,
		"SATURDAY":    6,
		"SUNDAY":      7,
	}
)

func (x ScheduleConfig_DayOfWeek) Enum() *ScheduleConfig_DayOfWeek {
	p := new(ScheduleConfig_DayOfWeek)
	*p = x
	return p
}

func (x ScheduleConfig_DayOfWeek) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScheduleConfig_DayOfWeek) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[3].Descriptor()
}

func (ScheduleConfig_DayOfWeek) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[3]
}

func (x ScheduleConfig_DayOfWeek) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScheduleConfig_DayOfWeek.Descriptor instead.
func (ScheduleConfig_DayOfWeek) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{8, 0}
}

// Message definitions
type NotificationMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basic scalar fields
	Id         string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title      string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content    string  `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp  int64   `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RetryCount int32   `protobuf:"varint,5,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	IsUrgent   bool    `protobuf:"varint,6,opt,name=is_urgent,json=isUrgent,proto3" json:"is_urgent,omitempty"`
	Cost       float64 `protobuf:"fixed64,7,opt,name=cost,proto3" json:"cost,omitempty"`
	Rating     float32 `protobuf:"fixed32,8,opt,name=rating,proto3" json:"rating,omitempty"`
	Signature  []byte  `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
	// Enum fields
	Type     NotificationType `protobuf:"varint,10,opt,name=type,proto3,enum=notification.NotificationType" json:"type,omitempty"`
	Priority Priority         `protobuf:"varint,11,opt,name=priority,proto3,enum=notification.Priority" json:"priority,omitempty"`
	Status   Status           `protobuf:"varint,12,opt,name=status,proto3,enum=notification.Status" json:"status,omitempty"`
	// Nested message
	Recipient *Recipient `protobuf:"bytes,13,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// Repeated fields
	Tags        []string      `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`
	Attachments []*Attachment `protobuf:"bytes,15,rep,name=attachments,proto3" json:"attachments,omitempty"`
	ErrorCodes  []int32       `protobuf:"varint,16,rep,packed,name=error_codes,json=errorCodes,proto3" json:"error_codes,omitempty"`
	// Map fields
	Metadata     map[string]string      `protobuf:"bytes,17,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metrics      map[int32]*MetricValue `protobuf:"bytes,18,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CcRecipients map[string]*Recipient  `protobuf:"bytes,19,rep,name=cc_recipients,json=ccRecipients,proto3" json:"cc_recipients,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Oneof fields
	//
	// Types that are valid to be assigned to Destination:
	//
	//	*NotificationMessage_EmailDest
	//	*NotificationMessage_SmsDest
	//	*NotificationMessage_PushDest
	//	*NotificationMessage_WebhookDest
	Destination isNotificationMessage_Destination `protobuf_oneof:"destination"`
	// Types that are valid to be assigned to Schedule:
	//
	//	*NotificationMessage_SendAtTimestamp
	//	*NotificationMessage_ScheduleConfig
	Schedule isNotificationMessage_Schedule `protobuf_oneof:"schedule"`
	// Optional fields (proto3 style)
	ExternalId    *string `protobuf:"bytes,26,opt,name=external_id,json=externalId,proto3,oneof" json:"external_id,omitempty"`
	TestMode      *bool   `protobuf:"varint,27,opt,name=test_mode,json=testMode,proto3,oneof" json:"test_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationMessage) Reset() {
	*x = NotificationMessage{}
	mi := &file_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationMessage) ProtoMessage() {}

func (x *NotificationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationMessage.ProtoReflect.Descriptor instead.
func (*NotificationMessage) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotificationMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NotificationMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *NotificationMessage) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *NotificationMessage) GetIsUrgent() bool {
	if x != nil {
		return x.IsUrgent
	}
	return false
}

func (x *NotificationMessage) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *NotificationMessage) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *NotificationMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *NotificationMessage) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_TYPE_UNKNOWN
}

func (x *NotificationMessage) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNKNOWN
}

func (x *NotificationMessage) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

func (x *NotificationMessage) GetRecipient() *Recipient {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *NotificationMessage) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *NotificationMessage) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *NotificationMessage) GetErrorCodes() []int32 {
	if x != nil {
		return x.ErrorCodes
	}
	return nil
}

func (x *NotificationMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *NotificationMessage) GetMetrics() map[int32]*MetricValue {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *NotificationMessage) GetCcRecipients() map[string]*Recipient {
	if x != nil {
		return x.CcRecipients
	}
	return nil
}

func (x *NotificationMessage) GetDestination() isNotificationMessage_Destination {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *NotificationMessage) GetEmailDest() *EmailDestination {
	if x != nil {
		if x, ok := x.Destination.(*NotificationMessage_EmailDest); ok {
			return x.EmailDest
		}
	}
	return nil
}

func (x *NotificationMessage) GetSmsDest() *SmsDestination {
	if x != nil {
		if x, ok := x.Destination.(*NotificationMessage_SmsDest); ok {
			return x.SmsDest
		}
	}
	return nil
}

func (x *NotificationMessage) GetPushDest() *PushDestination {
	if x != nil {
		if x, ok := x.Destination.(*NotificationMessage_PushDest); ok {
			return x.PushDest
		}
	}
	return nil
}

func (x *NotificationMessage) GetWebhookDest() *WebhookDestination {
	if x != nil {
		if x, ok := x.Destination.(*NotificationMessage_WebhookDest); ok {
			return x.WebhookDest
		}
	}
	return nil
}

func (x *NotificationMessage) GetSchedule() isNotificationMessage_Schedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *NotificationMessage) GetSendAtTimestamp() int64 {
	if x != nil {
		if x, ok := x.Schedule.(*NotificationMessage_SendAtTimestamp); ok {
			return x.SendAtTimestamp
		}
	}
	return 0
}

func (x *NotificationMessage) GetScheduleConfig() *ScheduleConfig {
	if x != nil {
		if x, ok := x.Schedule.(*NotificationMessage_ScheduleConfig); ok {
			return x.ScheduleConfig
		}
	}
	return nil
}

func (x *NotificationMessage) GetExternalId() string {
	if x != nil && x.ExternalId != nil {
		return *x.ExternalId
	}
	return ""
}

func (x *NotificationMessage) GetTestMode() bool {
	if x != nil && x.TestMode != nil {
		return *x.TestMode
	}
	return false
}

type isNotificationMessage_Destination interface {
	isNotificationMessage_Destination()
}

type NotificationMessage_EmailDest struct {
	EmailDest *EmailDestination `protobuf:"bytes,20,opt,name=email_dest,json=emailDest,proto3,oneof"`
}

type NotificationMessage_SmsDest struct {
	SmsDest *SmsDestination `protobuf:"bytes,21,opt,name=sms_dest,json=smsDest,proto3,oneof"`
}

type NotificationMessage_PushDest struct {
	PushDest *PushDestination `protobuf:"bytes,22,opt,name=push_dest,json=pushDest,proto3,oneof"`
}

type NotificationMessage_WebhookDest struct {
	WebhookDest *WebhookDestination `protobuf:"bytes,23,opt,name=webhook_dest,json=webhookDest,proto3,oneof"`
}

func (*NotificationMessage_EmailDest) isNotificationMessage_Destination() {}

func (*NotificationMessage_SmsDest) isNotificationMessage_Destination() {}

func (*NotificationMessage_PushDest) isNotificationMessage_Destination() {}

func (*NotificationMessage_WebhookDest) isNotificationMessage_Destination() {}

type isNotificationMessage_Schedule interface {
	isNotificationMessage_Schedule()
}

type NotificationMessage_SendAtTimestamp struct {
	SendAtTimestamp int64 `protobuf:"varint,24,opt,name=send_at_timestamp,json=sendAtTimestamp,proto3,oneof"`
}

type NotificationMessage_ScheduleConfig struct {
	ScheduleConfig *ScheduleConfig `protobuf:"bytes,25,opt,name=schedule_config,json=scheduleConfig,proto3,oneof"`
}

func (*NotificationMessage_SendAtTimestamp) isNotificationMessage_Schedule() {}

func (*NotificationMessage_ScheduleConfig) isNotificationMessage_Schedule() {}

type Recipient struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Name       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email      string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone      string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	UserId     int32                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Attributes map[string]string      `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*Recipient_EmailAddr
	//	*Recipient_PhoneNumber
	//	*Recipient_UserToken
	Identifier    isRecipient_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recipient) Reset() {
	*x = Recipient{}
	mi := &file_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipient) ProtoMessage() {}

func (x *Recipient) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipient.ProtoReflect.Descriptor instead.
func (*Recipient) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *Recipient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Recipient) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Recipient) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Recipient) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Recipient) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Recipient) GetIdentifier() isRecipient_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *Recipient) GetEmailAddr() string {
	if x != nil {
		if x, ok := x.Identifier.(*Recipient_EmailAddr); ok {
			return x.EmailAddr
		}
	}
	return ""
}

func (x *Recipient) GetPhoneNumber() string {
	if x != nil {
		if x, ok := x.Identifier.(*Recipient_PhoneNumber); ok {
			return x.PhoneNumber
		}
	}
	return ""
}

func (x *Recipient) GetUserToken() string {
	if x != nil {
		if x, ok := x.Identifier.(*Recipient_UserToken); ok {
			return x.UserToken
		}
	}
	return ""
}

type isRecipient_Identifier interface {
	isRecipient_Identifier()
}

type Recipient_EmailAddr struct {
	EmailAddr string `protobuf:"bytes,6,opt,name=email_addr,json=emailAddr,proto3,oneof"`
}

type Recipient_PhoneNumber struct {
	PhoneNumber string `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3,oneof"`
}

type Recipient_UserToken struct {
	UserToken string `protobuf:"bytes,8,opt,name=user_token,json=userToken,proto3,oneof"`
}

func (*Recipient_EmailAddr) isRecipient_Identifier() {}

func (*Recipient_PhoneNumber) isRecipient_Identifier() {}

func (*Recipient_UserToken) isRecipient_Identifier() {}

type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

func (x *Attachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Attachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Attachment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Attachment) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Attachment) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Attachment) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type MetricValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricValue) Reset() {
	*x = MetricValue{}
	mi := &file_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricValue) ProtoMessage() {}

func (x *MetricValue) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricValue.ProtoReflect.Descriptor instead.
func (*MetricValue) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{3}
}

func (x *MetricValue) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricValue) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *MetricValue) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Destination message types for oneof
type EmailDestination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	HtmlBody      string                 `protobuf:"bytes,3,opt,name=html_body,json=htmlBody,proto3" json:"html_body,omitempty"`
	TextBody      string                 `protobuf:"bytes,4,opt,name=text_body,json=textBody,proto3" json:"text_body,omitempty"`
	Cc            []string               `protobuf:"bytes,5,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc           []string               `protobuf:"bytes,6,rep,name=bcc,proto3" json:"bcc,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,7,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailDestination) Reset() {
	*x = EmailDestination{}
	mi := &file_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailDestination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailDestination) ProtoMessage() {}

func (x *EmailDestination) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailDestination.ProtoReflect.Descriptor instead.
func (*EmailDestination) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4}
}

func (x *EmailDestination) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailDestination) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailDestination) GetHtmlBody() string {
	if x != nil {
		return x.HtmlBody
	}
	return ""
}

func (x *EmailDestination) GetTextBody() string {
	if x != nil {
		return x.TextBody
	}
	return ""
}

func (x *EmailDestination) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *EmailDestination) GetBcc() []string {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *EmailDestination) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type SmsDestination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmsDestination) Reset() {
	*x = SmsDestination{}
	mi := &file_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmsDestination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsDestination) ProtoMessage() {}

func (x *SmsDestination) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsDestination.ProtoReflect.Descriptor instead.
func (*SmsDestination) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{5}
}

func (x *SmsDestination) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *SmsDestination) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SmsDestination) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

type PushDestination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceToken   string                 `protobuf:"bytes,1,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Data          map[string]string      `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Badge         int32                  `protobuf:"varint,5,opt,name=badge,proto3" json:"badge,omitempty"`
	Sound         string                 `protobuf:"bytes,6,opt,name=sound,proto3" json:"sound,omitempty"`
	Ttl           int64                  `protobuf:"varint,7,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushDestination) Reset() {
	*x = PushDestination{}
	mi := &file_test_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushDestination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushDestination) ProtoMessage() {}

func (x *PushDestination) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushDestination.ProtoReflect.Descriptor instead.
func (*PushDestination) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{6}
}

func (x *PushDestination) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

func (x *PushDestination) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PushDestination) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *PushDestination) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PushDestination) GetBadge() int32 {
	if x != nil {
		return x.Badge
	}
	return 0
}

func (x *PushDestination) GetSound() string {
	if x != nil {
		return x.Sound
	}
	return ""
}

func (x *PushDestination) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type WebhookDestination struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Url            string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method         string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Headers        map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Payload        string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WebhookDestination) Reset() {
	*x = WebhookDestination{}
	mi := &file_test_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookDestination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookDestination) ProtoMessage() {}

func (x *WebhookDestination) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookDestination.ProtoReflect.Descriptor instead.
func (*WebhookDestination) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{7}
}

func (x *WebhookDestination) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WebhookDestination) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *WebhookDestination) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *WebhookDestination) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *WebhookDestination) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ScheduleConfig struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	StartTime       int64                      `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime         int64                      `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	DaysOfWeek      []ScheduleConfig_DayOfWeek `protobuf:"varint,3,rep,packed,name=days_of_week,json=daysOfWeek,proto3,enum=notification.ScheduleConfig_DayOfWeek" json:"days_of_week,omitempty"`
	Timezone        string                     `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`
	IntervalMinutes int32                      `protobuf:"varint,5,opt,name=interval_minutes,json=intervalMinutes,proto3" json:"interval_minutes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScheduleConfig) Reset() {
	*x = ScheduleConfig{}
	mi := &file_test_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleConfig) ProtoMessage() {}

func (x *ScheduleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleConfig.ProtoReflect.Descriptor instead.
func (*ScheduleConfig) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{8}
}

func (x *ScheduleConfig) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ScheduleConfig) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *ScheduleConfig) GetDaysOfWeek() []ScheduleConfig_DayOfWeek {
	if x != nil {
		return x.DaysOfWeek
	}
	return nil
}

func (x *ScheduleConfig) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *ScheduleConfig) GetIntervalMinutes() int32 {
	if x != nil {
		return x.IntervalMinutes
	}
	return 0
}

// Additional complex message for testing nested structures
type Campaign struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Id            string                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Notifications []*NotificationMessage      `protobuf:"bytes,3,rep,name=notifications,proto3" json:"notifications,omitempty"`
	MetricsByType map[string]*CampaignMetrics `protobuf:"bytes,4,rep,name=metrics_by_type,json=metricsByType,proto3" json:"metrics_by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Targeting:
	//
	//	*Campaign_Segment
	//	*Campaign_Individuals
	Targeting     isCampaign_Targeting `protobuf_oneof:"targeting"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Campaign) Reset() {
	*x = Campaign{}
	mi := &file_test_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Campaign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Campaign) ProtoMessage() {}

func (x *Campaign) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Campaign.ProtoReflect.Descriptor instead.
func (*Campaign) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{9}
}

func (x *Campaign) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Campaign) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Campaign) GetNotifications() []*NotificationMessage {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *Campaign) GetMetricsByType() map[string]*CampaignMetrics {
	if x != nil {
		return x.MetricsByType
	}
	return nil
}

func (x *Campaign) GetTargeting() isCampaign_Targeting {
	if x != nil {
		return x.Targeting
	}
	return nil
}

func (x *Campaign) GetSegment() *SegmentTargeting {
	if x != nil {
		if x, ok := x.Targeting.(*Campaign_Segment); ok {
			return x.Segment
		}
	}
	return nil
}

func (x *Campaign) GetIndividuals() *IndividualTargeting {
	if x != nil {
		if x, ok := x.Targeting.(*Campaign_Individuals); ok {
			return x.Individuals
		}
	}
	return nil
}

type isCampaign_Targeting interface {
	isCampaign_Targeting()
}

type Campaign_Segment struct {
	Segment *SegmentTargeting `protobuf:"bytes,5,opt,name=segment,proto3,oneof"`
}

type Campaign_Individuals struct {
	Individuals *IndividualTargeting `protobuf:"bytes,6,opt,name=individuals,proto3,oneof"`
}

func (*Campaign_Segment) isCampaign_Targeting() {}

func (*Campaign_Individuals) isCampaign_Targeting() {}

type CampaignMetrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SentCount      int64                  `protobuf:"varint,1,opt,name=sent_count,json=sentCount,proto3" json:"sent_count,omitempty"`
	DeliveredCount int64                  `protobuf:"varint,2,opt,name=delivered_count,json=deliveredCount,proto3" json:"delivered_count,omitempty"`
	FailedCount    int64                  `protobuf:"varint,3,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	SuccessRate    float64                `protobuf:"fixed64,4,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CampaignMetrics) Reset() {
	*x = CampaignMetrics{}
	mi := &file_test_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignMetrics) ProtoMessage() {}

func (x *CampaignMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignMetrics.ProtoReflect.Descriptor instead.
func (*CampaignMetrics) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{10}
}

func (x *CampaignMetrics) GetSentCount() int64 {
	if x != nil {
		return x.SentCount
	}
	return 0
}

func (x *CampaignMetrics) GetDeliveredCount() int64 {
	if x != nil {
		return x.DeliveredCount
	}
	return 0
}

func (x *CampaignMetrics) GetFailedCount() int64 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *CampaignMetrics) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

type SegmentTargeting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentId     string                 `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	Filters       []string               `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
	MaxRecipients int32                  `protobuf:"varint,3,opt,name=max_recipients,json=maxRecipients,proto3" json:"max_recipients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentTargeting) Reset() {
	*x = SegmentTargeting{}
	mi := &file_test_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentTargeting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentTargeting) ProtoMessage() {}

func (x *SegmentTargeting) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentTargeting.ProtoReflect.Descriptor instead.
func (*SegmentTargeting) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{11}
}

func (x *SegmentTargeting) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *SegmentTargeting) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SegmentTargeting) GetMaxRecipients() int32 {
	if x != nil {
		return x.MaxRecipients
	}
	return 0
}

type IndividualTargeting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipients    []*Recipient           `protobuf:"bytes,1,rep,name=recipients,proto3" json:"recipients,omitempty"`
	Deduplicate   bool                   `protobuf:"varint,2,opt,name=deduplicate,proto3" json:"deduplicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndividualTargeting) Reset() {
	*x = IndividualTargeting{}
	mi := &file_test_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndividualTargeting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndividualTargeting) ProtoMessage() {}

func (x *IndividualTargeting) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndividualTargeting.ProtoReflect.Descriptor instead.
func (*IndividualTargeting) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{12}
}

func (x *IndividualTargeting) GetRecipients() []*Recipient {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *IndividualTargeting) GetDeduplicate() bool {
	if x != nil {
		return x.Deduplicate
	}
	return false
}

var File_test_proto protoreflect.FileDescriptor

const file_test_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"test.proto\x12\fnotification\"\x91\f\n" +
	"\x13NotificationMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vretry_count\x18\x05 \x01(\x05R\n" +
	"retryCount\x12\x1b\n" +
	"\tis_urgent\x18\x06 \x01(\bR\bisUrgent\x12\x12\n" +
	"\x04cost\x18\a \x01(\x01R\x04cost\x12\x16\n" +
	"\x06rating\x18\b \x01(\x02R\x06rating\x12\x1c\n" +
	"\tsignature\x18\t \x01(\fR\tsignature\x122\n" +
	"\x04type\x18\n" +
	" \x01(\x0e2\x1e.notification.NotificationTypeR\x04type\x122\n" +
	"\bpriority\x18\v \x01(\x0e2\x16.notification.PriorityR\bpriority\x12,\n" +
	"\x06status\x18\f \x01(\x0e2\x14.notification.StatusR\x06status\x125\n" +
	"\trecipient\x18\r \x01(\v2\x17.notification.RecipientR\trecipient\x12\x12\n" +
	"\x04tags\x18\x0e \x03(\tR\x04tags\x12:\n" +
	"\vattachments\x18\x0f \x03(\v2\x18.notification.AttachmentR\vattachments\x12\x1f\n" +
	"\verror_codes\x18\x10 \x03(\x05R\n" +
	"errorCodes\x12K\n" +
	"\bmetadata\x18\x11 \x03(\v2/.notification.NotificationMessage.MetadataEntryR\bmetadata\x12H\n" +
	"\ametrics\x18\x12 \x03(\v2..notification.NotificationMessage.MetricsEntryR\ametrics\x12X\n" +
	"\rcc_recipients\x18\x13 \x03(\v23.notification.NotificationMessage.CcRecipientsEntryR\fccRecipients\x12?\n" +
	"\n" +
	"email_dest\x18\x14 \x01(\v2\x1e.notification.EmailDestinationH\x00R\temailDest\x129\n" +
	"\bsms_dest\x18\x15 \x01(\v2\x1c.notification.SmsDestinationH\x00R\asmsDest\x12<\n" +
	"\tpush_dest\x18\x16 \x01(\v2\x1d.notification.PushDestinationH\x00R\bpushDest\x12E\n" +
	"\fwebhook_dest\x18\x17 \x01(\v2 .notification.WebhookDestinationH\x00R\vwebhookDest\x12,\n" +
	"\x11send_at_timestamp\x18\x18 \x01(\x03H\x01R\x0fsendAtTimestamp\x12G\n" +
	"\x0fschedule_config\x18\x19 \x01(\v2\x1c.notification.ScheduleConfigH\x01R\x0escheduleConfig\x12$\n" +
	"\vexternal_id\x18\x1a \x01(\tH\x02R\n" +
	"externalId\x88\x01\x01\x12 \n" +
	"\ttest_mode\x18\x1b \x01(\bH\x03R\btestMode\x88\x01\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aU\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.notification.MetricValueR\x05value:\x028\x01\x1aX\n" +
	"\x11CcRecipientsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.notification.RecipientR\x05value:\x028\x01B\r\n" +
	"\vdestinationB\n" +
	"\n" +
	"\bscheduleB\x0e\n" +
	"\f_external_idB\f\n" +
	"\n" +
	"_test_mode\"\xe1\x02\n" +
	"\tRecipient\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x05R\x06userId\x12G\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v2'.notification.Recipient.AttributesEntryR\n" +
	"attributes\x12\x1f\n" +
	"\n" +
	"email_addr\x18\x06 \x01(\tH\x00R\temailAddr\x12#\n" +
	"\fphone_number\x18\a \x01(\tH\x00R\vphoneNumber\x12\x1f\n" +
	"\n" +
	"user_token\x18\b \x01(\tH\x00R\tuserToken\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"identifier\"\x82\x02\n" +
	"\n" +
	"Attachment\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12?\n" +
	"\aheaders\x18\x06 \x03(\v2%.notification.Attachment.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\vMetricValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\xa1\x02\n" +
	"\x10EmailDestination\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1b\n" +
	"\thtml_body\x18\x03 \x01(\tR\bhtmlBody\x12\x1b\n" +
	"\ttext_body\x18\x04 \x01(\tR\btextBody\x12\x0e\n" +
	"\x02cc\x18\x05 \x03(\tR\x02cc\x12\x10\n" +
	"\x03bcc\x18\x06 \x03(\tR\x03bcc\x12E\n" +
	"\aheaders\x18\a \x03(\v2+.notification.EmailDestination.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\x0eSmsDestination\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\"\x92\x02\n" +
	"\x0fPushDestination\x12!\n" +
	"\fdevice_token\x18\x01 \x01(\tR\vdeviceToken\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12;\n" +
	"\x04data\x18\x04 \x03(\v2'.notification.PushDestination.DataEntryR\x04data\x12\x14\n" +
	"\x05badge\x18\x05 \x01(\x05R\x05badge\x12\x14\n" +
	"\x05sound\x18\x06 \x01(\tR\x05sound\x12\x10\n" +
	"\x03ttl\x18\a \x01(\x03R\x03ttl\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x02\n" +
	"\x12WebhookDestination\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12G\n" +
	"\aheaders\x18\x03 \x03(\v2-.notification.WebhookDestination.HeadersEntryR\aheaders\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd5\x02\n" +
	"\x0eScheduleConfig\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x03R\aendTime\x12H\n" +
	"\fdays_of_week\x18\x03 \x03(\x0e2&.notification.ScheduleConfig.DayOfWeekR\n" +
	"daysOfWeek\x12\x1a\n" +
	"\btimezone\x18\x04 \x01(\tR\btimezone\x12)\n" +
	"\x10interval_minutes\x18\x05 \x01(\x05R\x0fintervalMinutes\"x\n" +
	"\tDayOfWeek\x12\x0f\n" +
	"\vDAY_UNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06MONDAY\x10\x01\x12\v\n" +
	"\aTUESDAY\x10\x02\x12\r\n" +
	"\tWEDNESDAY\x10\x03\x12\f\n" +
	"\bTHURSDAY\x10\x04\x12\n" +
	"\n" +
	"\x06FRIDAY\x10\x05\x12\f\n" +
	"\bSATURDAY\x10\x06\x12\n" +
	"\n" +
	"\x06SUNDAY\x10\a\"\xbb\x03\n" +
	"\bCampaign\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12G\n" +
	"\rnotifications\x18\x03 \x03(\v2!.notification.NotificationMessageR\rnotifications\x12Q\n" +
	"\x0fmetrics_by_type\x18\x04 \x03(\v2).notification.Campaign.MetricsByTypeEntryR\rmetricsByType\x12:\n" +
	"\asegment\x18\x05 \x01(\v2\x1e.notification.SegmentTargetingH\x00R\asegment\x12E\n" +
	"\vindividuals\x18\x06 \x01(\v2!.notification.IndividualTargetingH\x00R\vindividuals\x1a_\n" +
	"\x12MetricsByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.notification.CampaignMetricsR\x05value:\x028\x01B\v\n" +
	"\ttargeting\"\x9f\x01\n" +
	"\x0fCampaignMetrics\x12\x1d\n" +
	"\n" +
	"sent_count\x18\x01 \x01(\x03R\tsentCount\x12'\n" +
	"\x0fdelivered_count\x18\x02 \x01(\x03R\x0edeliveredCount\x12!\n" +
	"\ffailed_count\x18\x03 \x01(\x03R\vfailedCount\x12!\n" +
	"\fsuccess_rate\x18\x04 \x01(\x01R\vsuccessRate\"r\n" +
	"\x10SegmentTargeting\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\tR\tsegmentId\x12\x18\n" +
	"\afilters\x18\x02 \x03(\tR\afilters\x12%\n" +
	"\x0emax_recipients\x18\x03 \x01(\x05R\rmaxRecipients\"p\n" +
	"\x13IndividualTargeting\x127\n" +
	"\n" +
	"recipients\x18\x01 \x03(\v2\x17.notification.RecipientR\n" +
	"recipients\x12 \n" +
	"\vdeduplicate\x18\x02 \x01(\bR\vdeduplicate*c\n" +
	"\x10NotificationType\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"TYPE_EMAIL\x10\x01\x12\f\n" +
	"\bTYPE_SMS\x10\x02\x12\r\n" +
	"\tTYPE_PUSH\x10\x03\x12\x10\n" +
	"\fTYPE_WEBHOOK\x10\x04*o\n" +
	"\bPriority\x12\x14\n" +
	"\x10PRIORITY_UNKNOWN\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_MEDIUM\x10\x02\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x03\x12\x13\n" +
	"\x0fPRIORITY_URGENT\x10\x04*j\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x01\x12\x0f\n" +
	"\vSTATUS_SENT\x10\x02\x12\x14\n" +
	"\x10STATUS_DELIVERED\x10\x03\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x04B\x16Z\x14example/notificationb\x06proto3"

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData []byte
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)))
	})
	return file_test_proto_rawDescData
}

var file_test_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_test_proto_goTypes = []any{
	(NotificationType)(0),         // 0: notification.NotificationType
	(Priority)(0),                 // 1: notification.Priority
	(Status)(0),                   // 2: notification.Status
	(ScheduleConfig_DayOfWeek)(0), // 3: notification.ScheduleConfig.DayOfWeek
	(*NotificationMessage)(nil),   // 4: notification.NotificationMessage
	(*Recipient)(nil),             // 5: notification.Recipient
	(*Attachment)(nil),            // 6: notification.Attachment
	(*MetricValue)(nil),           // 7: notification.MetricValue
	(*EmailDestination)(nil),      // 8: notification.EmailDestination
	(*SmsDestination)(nil),        // 9: notification.SmsDestination
	(*PushDestination)(nil),       // 10: notification.PushDestination
	(*WebhookDestination)(nil),    // 11: notification.WebhookDestination
	(*ScheduleConfig)(nil),        // 12: notification.ScheduleConfig
	(*Campaign)(nil),              // 13: notification.Campaign
	(*CampaignMetrics)(nil),       // 14: notification.CampaignMetrics
	(*SegmentTargeting)(nil),      // 15: notification.SegmentTargeting
	(*IndividualTargeting)(nil),   // 16: notification.IndividualTargeting
	nil,                           // 17: notification.NotificationMessage.MetadataEntry
	nil,                           // 18: notification.NotificationMessage.MetricsEntry
	nil,                           // 19: notification.NotificationMessage.CcRecipientsEntry
	nil,                           // 20: notification.Recipient.AttributesEntry
	nil,                           // 21: notification.Attachment.HeadersEntry
	nil,                           // 22: notification.EmailDestination.HeadersEntry
	nil,                           // 23: notification.PushDestination.DataEntry
	nil,                           // 24: notification.WebhookDestination.HeadersEntry
	nil,                           // 25: notification.Campaign.MetricsByTypeEntry
}
var file_test_proto_depIdxs = []int32{
	0,  // 0: notification.NotificationMessage.type:type_name -> notification.NotificationType
	1,  // 1: notification.NotificationMessage.priority:type_name -> notification.Priority
	2,  // 2: notification.NotificationMessage.status:type_name -> notification.Status
	5,  // 3: notification.NotificationMessage.recipient:type_name -> notification.Recipient
	6,  // 4: notification.NotificationMessage.attachments:type_name -> notification.Attachment
	17, // 5: notification.NotificationMessage.metadata:type_name -> notification.NotificationMessage.MetadataEntry
	18, // 6: notification.NotificationMessage.metrics:type_name -> notification.NotificationMessage.MetricsEntry
	19, // 7: notification.NotificationMessage.cc_recipients:type_name -> notification.NotificationMessage.CcRecipientsEntry
	8,  // 8: notification.NotificationMessage.email_dest:type_name -> notification.EmailDestination
	9,  // 9: notification.NotificationMessage.sms_dest:type_name -> notification.SmsDestination
	10, // 10: notification.NotificationMessage.push_dest:type_name -> notification.PushDestination
	11, // 11: notification.NotificationMessage.webhook_dest:type_name -> notification.WebhookDestination
	12, // 12: notification.NotificationMessage.schedule_config:type_name -> notification.ScheduleConfig
	20, // 13: notification.Recipient.attributes:type_name -> notification.Recipient.AttributesEntry
	21, // 14: notification.Attachment.headers:type_name -> notification.Attachment.HeadersEntry
	22, // 15: notification.EmailDestination.headers:type_name -> notification.EmailDestination.HeadersEntry
	23, // 16: notification.PushDestination.data:type_name -> notification.PushDestination.DataEntry
	24, // 17: notification.WebhookDestination.headers:type_name -> notification.WebhookDestination.HeadersEntry
	3,  // 18: notification.ScheduleConfig.days_of_week:type_name -> notification.ScheduleConfig.DayOfWeek
	4,  // 19: notification.Campaign.notifications:type_name -> notification.NotificationMessage
	25, // 20: notification.Campaign.metrics_by_type:type_name -> notification.Campaign.MetricsByTypeEntry
	15, // 21: notification.Campaign.segment:type_name -> notification.SegmentTargeting
	16, // 22: notification.Campaign.individuals:type_name -> notification.IndividualTargeting
	5,  // 23: notification.IndividualTargeting.recipients:type_name -> notification.Recipient
	7,  // 24: notification.NotificationMessage.MetricsEntry.value:type_name -> notification.MetricValue
	5,  // 25: notification.NotificationMessage.CcRecipientsEntry.value:type_name -> notification.Recipient
	14, // 26: notification.Campaign.MetricsByTypeEntry.value:type_name -> notification.CampaignMetrics
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	file_test_proto_msgTypes[0].OneofWrappers = []any{
		(*NotificationMessage_EmailDest)(nil),
		(*NotificationMessage_SmsDest)(nil),
		(*NotificationMessage_PushDest)(nil),
		(*NotificationMessage_WebhookDest)(nil),
		(*NotificationMessage_SendAtTimestamp)(nil),
		(*NotificationMessage_ScheduleConfig)(nil),
	}
	file_test_proto_msgTypes[1].OneofWrappers = []any{
		(*Recipient_EmailAddr)(nil),
		(*Recipient_PhoneNumber)(nil),
		(*Recipient_UserToken)(nil),
	}
	file_test_proto_msgTypes[9].OneofWrappers = []any{
		(*Campaign_Segment)(nil),
		(*Campaign_Individuals)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		EnumInfos:         file_test_proto_enumTypes,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
